/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clients;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aubrey Rose Undang
 */
public class addclients extends javax.swing.JFrame {

    /**
     * Creates new form addclients
     */
    public addclients() {
        initComponents();
    }

    addclients(String trim, String trim0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        deal_id = new javax.swing.JLabel();
        property_location = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        property_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        property_type = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        deal_amount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addclients = new javax.swing.JButton();
        deal_date = new javax.swing.JTextField();
        client_id = new javax.swing.JTextField();
        agent_id = new javax.swing.JTextField();
        deal_status = new javax.swing.JComboBox<>();
        approval_date = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(241, 224, 224));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deal_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deal_id.setText("Deal ID");
        jPanel4.add(deal_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        property_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                property_locationActionPerformed(evt);
            }
        });
        jPanel4.add(property_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 40));

        jLabel1.setText("Property Name:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel4.add(property_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 40));

        jLabel2.setText("Property Location:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        property_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "House", "Lot", "Condo" }));
        jPanel4.add(property_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 30));

        jLabel3.setText("Property Type:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        deal_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deal_amountActionPerformed(evt);
            }
        });
        jPanel4.add(deal_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 190, 40));

        jLabel4.setText("Amount:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel5.setText("status:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel6.setText("Date:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jLabel7.setText("Created:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        addclients.setText("Enter");
        addclients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclientsActionPerformed(evt);
            }
        });
        jPanel4.add(addclients, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 90, 30));

        deal_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deal_dateActionPerformed(evt);
            }
        });
        jPanel4.add(deal_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 190, 30));
        jPanel4.add(client_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 70, -1));
        jPanel4.add(agent_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, -1));

        deal_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ongoing", "Completed", "Cancelled" }));
        jPanel4.add(deal_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 190, 30));
        jPanel4.add(approval_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 190, 30));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void property_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_property_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_property_locationActionPerformed

    private void deal_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deal_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deal_amountActionPerformed

    private void addclientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclientsActionPerformed
        try {
            // 1. DB connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/landdealersystem", "root", "");

            // 2. SQL insert statement
            String sql = "INSERT INTO tbl_property_deal (client_id, agent_id, property_name, property_location, property_type, deal_amount, deal_status, approval_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(client_id.getText()));
            pst.setInt(2, Integer.parseInt(agent_id.getText()));
            pst.setString(3, property_name.getText());
            pst.setString(4, property_location.getText());
            pst.setString(5, property_type.getSelectedItem().toString());
            pst.setDouble(6, Double.parseDouble(deal_amount.getText()));
            pst.setString(7, deal_status.getSelectedItem().toString());
            pst.setString(8, approval_date.getText()); // Format: "YYYY-MM-DD"

            int rows = pst.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Client deal added successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add client deal.");
            }

            pst.close();
            conn.close();

        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    
    }//GEN-LAST:event_addclientsActionPerformed

    private void deal_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deal_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deal_dateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addclients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addclients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addclients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addclients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addclients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addclients;
    private javax.swing.JTextField agent_id;
    private javax.swing.JTextField approval_date;
    private javax.swing.JTextField client_id;
    private javax.swing.JTextField deal_amount;
    private javax.swing.JTextField deal_date;
    private javax.swing.JLabel deal_id;
    private javax.swing.JComboBox<String> deal_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField property_location;
    private javax.swing.JTextField property_name;
    private javax.swing.JComboBox<String> property_type;
    // End of variables declaration//GEN-END:variables
}
