/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admindashboard;

import config.dbConnectors;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aubrey Rose Undang
 */
public class adduserform extends javax.swing.JFrame {

    /**
     * Creates new form adduserform
     */
    public adduserform() {
        initComponents();
    }
    
    public boolean duplicateChecker() {
    dbConnectors dbc = new dbConnectors();
    String query = "SELECT u_email, u_username FROM tbl_user WHERE u_username = ? OR u_email = ?";

    try {
        PreparedStatement pst = dbc.getConnection().prepareStatement(query);
        pst.setString(1, uname.getText());
        pst.setString(2, eml.getText());

        ResultSet resultSet = pst.executeQuery();

        while (resultSet.next()) {
            String existingEmail = resultSet.getString("u_email");
            String existingUsername = resultSet.getString("u_username");

            if (existingEmail.equals(eml.getText())) {
                JOptionPane.showMessageDialog(null, "Email is Already Used!");
                eml.setText("");
                return true;
            }
            if (existingUsername.equals(uname.getText())) {
                JOptionPane.showMessageDialog(null, "Username is Already Taken!");
                uname.setText("");
                return true;
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace(); // Print errors for debugging 
    }
    return false;
}
    
    public boolean updateCheck() {
    dbConnectors dbc = new dbConnectors();
    // Don't use question marks if you're directly embedding values in the query string
    String query = "SELECT u_email, u_username FROM tbl_user WHERE (u_username = '"+uname.getText()+"' OR u_email = '"+eml.getText()+"') AND u_id != '"+uid.getText()+"'";

    try {
        // Execute the query directly without preparing
        ResultSet resultSet = dbc.getData(query);

        while (resultSet.next()) {
            String existingEmail = resultSet.getString("u_email");
            String existingUsername = resultSet.getString("u_username");

            if (existingEmail.equals(eml.getText())) {
                JOptionPane.showMessageDialog(null, "Email is Already Used!");
                eml.setText("");
                return true;
            }
            if (existingUsername.equals(uname.getText())) {
                JOptionPane.showMessageDialog(null, "Username is Already Taken!");
                uname.setText("");
                return true;
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace(); // Print errors for debugging
    }
    return false;
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        upass = new javax.swing.JPasswordField();
        uname = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        utype = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        eml = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        us = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        del = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 224, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        upass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        upass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upassActionPerformed(evt);
            }
        });
        jPanel1.add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 250, 40));

        uname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        uname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 250, 40));

        ln.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ln.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        ln.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 250, 40));

        jLabel8.setFont(jLabel8.getFont().deriveFont((float)15));
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("User Status:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        fn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        fn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 250, 40));

        utype.setBackground(new java.awt.Color(241, 224, 224));
        utype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        utype.setForeground(new java.awt.Color(102, 102, 102));
        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        utype.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        utype.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        utype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utypeActionPerformed(evt);
            }
        });
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 250, 40));

        add.setBackground(new java.awt.Color(241, 224, 224));
        add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(102, 102, 102));
        add.setText("ADD");
        add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, 40));

        jLabel12.setFont(jLabel12.getFont().deriveFont((float)15));
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("First Name:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jLabel13.setFont(jLabel13.getFont().deriveFont((float)15));
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Last Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        eml.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eml.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        eml.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        eml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emlActionPerformed(evt);
            }
        });
        jPanel1.add(eml, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 250, 40));

        jLabel14.setFont(jLabel14.getFont().deriveFont((float)15));
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Email:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel15.setFont(jLabel15.getFont().deriveFont((float)15));
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Username:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel9.setFont(jLabel9.getFont().deriveFont((float)15));
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logos.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 50));

        us.setBackground(new java.awt.Color(241, 224, 224));
        us.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        us.setForeground(new java.awt.Color(102, 102, 102));
        us.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acitve", "In-Active" }));
        us.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        us.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });
        jPanel1.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 250, 40));

        jLabel10.setFont(jLabel10.getFont().deriveFont((float)15));
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("User Type:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        uid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        uid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        uid.setEnabled(false);
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        jPanel1.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 250, 40));

        jLabel16.setFont(jLabel16.getFont().deriveFont((float)15));
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("User ID:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        update.setBackground(new java.awt.Color(241, 224, 224));
        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(102, 102, 102));
        update.setText("UPDATE");
        update.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, 40));

        del.setBackground(new java.awt.Color(241, 224, 224));
        del.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        del.setForeground(new java.awt.Color(102, 102, 102));
        del.setText("DELETE");
        del.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        del.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel1.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 90, 40));

        clear.setBackground(new java.awt.Color(241, 224, 224));
        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(102, 102, 102));
        clear.setText("CLEAR");
        clear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 90, 40));

        refresh.setBackground(new java.awt.Color(241, 224, 224));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        refresh.setForeground(new java.awt.Color(102, 102, 102));
        refresh.setText("REFRESH");
        refresh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 90, 40));

        cancel.setBackground(new java.awt.Color(241, 224, 224));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(102, 102, 102));
        cancel.setText("CANCEL");
        cancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(818, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upassActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void utypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utypeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    
        
        
        if(fn.getText().isEmpty()||ln.getText().isEmpty()||eml.getText().isEmpty()||uname.getText().isEmpty()||upass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Feilds are required!");
        }else if(upass.getText().length()<8){
            JOptionPane.showMessageDialog(null,"Password character should be 8 above");
            upass.setText("");
        }else if(duplicateChecker()){
            System.out.println("Duplicate Exits");
        }else{
            dbConnectors dbc = new dbConnectors();
            if (dbc.insertData("INSERT INTO tbl_user(u_fname, u_lname, u_email, u_username, u_password, u_type, u_status) "
                + "VALUES('" + fn.getText() + "','" + ln.getText() + "','" + eml.getText() + "','"
                + uname.getText() + "','" + upass.getText() + "','" + utype.getSelectedItem() + "','"+us.getSelectedItem()+"')") == 1) {
            JOptionPane.showMessageDialog(null, "Created Successfully");
            usersform uf = new usersform();
            uf.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Sign Up Unsuccessfully");
        }

        }

    }//GEN-LAST:event_addActionPerformed

    private void emlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emlActionPerformed

    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        if(fn.getText().isEmpty()||ln.getText().isEmpty()||eml.getText().isEmpty()||uname.getText().isEmpty()||upass.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"All Fields are required!");
    } else if(upass.getText().length()<8){
        JOptionPane.showMessageDialog(null,"Password character should be 8 above");
        upass.setText("");
    } else if(updateCheck()){
        System.out.println("Duplicate Exists");
    } else {
    
        dbConnectors dbc = new dbConnectors();
        
        dbc.updateData("UPDATE tbl_user SET u_fname = '"+fn.getText()+"',u_lname = '"+ln.getText()+"'"
                + ",u_email = '"+eml.getText()+"',u_username = '"+uname.getText()+"',u_password = '"+upass.getText()+"'"
                + ",u_type = '"+utype.getSelectedItem()+"',u_status = '"+us.getSelectedItem()+"' WHERE u_id ='"+uid.getText()+"'");
        
        usersform uf = new usersform();
        uf.setVisible(true);
        this.dispose();
    }

    }//GEN-LAST:event_updateActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        usersform uf = new usersform();
        uf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adduserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adduserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adduserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adduserform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adduserform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    public javax.swing.JTextField eml;
    public javax.swing.JTextField fn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField ln;
    private javax.swing.JButton refresh;
    public javax.swing.JTextField uid;
    public javax.swing.JTextField uname;
    public javax.swing.JPasswordField upass;
    public javax.swing.JButton update;
    public javax.swing.JComboBox<String> us;
    public javax.swing.JComboBox<String> utype;
    // End of variables declaration//GEN-END:variables
}
